/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppRecursosRouteImport } from './routes/app.recursos'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMisionesRouteImport } from './routes/app.misiones'
import { Route as AppMascotaRouteImport } from './routes/app.mascota'
import { Route as AppJuegosRouteImport } from './routes/app.juegos'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppAvatarRouteImport } from './routes/app.avatar'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AdminNoticiasRouteImport } from './routes/admin.noticias'
import { Route as AdminEstudiantesRouteImport } from './routes/admin.estudiantes'
import { Route as AdminEncuestasRouteImport } from './routes/admin.encuestas'
import { Route as AdminAlertasRouteImport } from './routes/admin.alertas'
import { Route as AppJuegosIndexRouteImport } from './routes/app.juegos.index'
import { Route as AppJuegosTriviaRouteImport } from './routes/app.juegos.trivia'
import { Route as AppJuegosSemaforoRouteImport } from './routes/app.juegos.semaforo'
import { Route as AppJuegosRespiraRouteImport } from './routes/app.juegos.respira'
import { Route as AppJuegosMemoramaRouteImport } from './routes/app.juegos.memorama'
import { Route as AppJuegosGratitudRouteImport } from './routes/app.juegos.gratitud'
import { Route as AppJuegosEscudoRouteImport } from './routes/app.juegos.escudo'
import { Route as AppJuegosConexionRouteImport } from './routes/app.juegos.conexion'
import { Route as AppJuegosCazadoresRouteImport } from './routes/app.juegos.cazadores'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppRecursosRoute = AppRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMisionesRoute = AppMisionesRouteImport.update({
  id: '/misiones',
  path: '/misiones',
  getParentRoute: () => AppRoute,
} as any)
const AppMascotaRoute = AppMascotaRouteImport.update({
  id: '/mascota',
  path: '/mascota',
  getParentRoute: () => AppRoute,
} as any)
const AppJuegosRoute = AppJuegosRouteImport.update({
  id: '/juegos',
  path: '/juegos',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAvatarRoute = AppAvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticiasRoute = AdminNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstudiantesRoute = AdminEstudiantesRouteImport.update({
  id: '/estudiantes',
  path: '/estudiantes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEncuestasRoute = AdminEncuestasRouteImport.update({
  id: '/encuestas',
  path: '/encuestas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertasRoute = AdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminRoute,
} as any)
const AppJuegosIndexRoute = AppJuegosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJuegosRoute,
} as any)
const AppJuegosTriviaRoute = AppJuegosTriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => AppJuegosRoute,
} as any)
const AppJuegosSemaforoRoute = AppJuegosSemaforoRouteImport.update({
  id: '/semaforo',
  path: '/semaforo',
  getParentRoute: () => AppJuegosRoute,
} as any)
const AppJuegosRespiraRoute = AppJuegosRespiraRouteImport.update({
  id: '/respira',
  path: '/respira',
  getParentRoute: () => AppJuegosRoute,
} as any)
const AppJuegosMemoramaRoute = AppJuegosMemoramaRouteImport.update({
  id: '/memorama',
  path: '/memorama',
  getParentRoute: () => AppJuegosRoute,
} as any)
const AppJuegosGratitudRoute = AppJuegosGratitudRouteImport.update({
  id: '/gratitud',
  path: '/gratitud',
  getParentRoute: () => AppJuegosRoute,
} as any)
const AppJuegosEscudoRoute = AppJuegosEscudoRouteImport.update({
  id: '/escudo',
  path: '/escudo',
  getParentRoute: () => AppJuegosRoute,
} as any)
const AppJuegosConexionRoute = AppJuegosConexionRouteImport.update({
  id: '/conexion',
  path: '/conexion',
  getParentRoute: () => AppJuegosRoute,
} as any)
const AppJuegosCazadoresRoute = AppJuegosCazadoresRouteImport.update({
  id: '/cazadores',
  path: '/cazadores',
  getParentRoute: () => AppJuegosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/encuestas': typeof AdminEncuestasRoute
  '/admin/estudiantes': typeof AdminEstudiantesRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/api/chat': typeof ApiChatRoute
  '/app/avatar': typeof AppAvatarRoute
  '/app/chat': typeof AppChatRoute
  '/app/juegos': typeof AppJuegosRouteWithChildren
  '/app/mascota': typeof AppMascotaRoute
  '/app/misiones': typeof AppMisionesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/recursos': typeof AppRecursosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/juegos/cazadores': typeof AppJuegosCazadoresRoute
  '/app/juegos/conexion': typeof AppJuegosConexionRoute
  '/app/juegos/escudo': typeof AppJuegosEscudoRoute
  '/app/juegos/gratitud': typeof AppJuegosGratitudRoute
  '/app/juegos/memorama': typeof AppJuegosMemoramaRoute
  '/app/juegos/respira': typeof AppJuegosRespiraRoute
  '/app/juegos/semaforo': typeof AppJuegosSemaforoRoute
  '/app/juegos/trivia': typeof AppJuegosTriviaRoute
  '/app/juegos/': typeof AppJuegosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/encuestas': typeof AdminEncuestasRoute
  '/admin/estudiantes': typeof AdminEstudiantesRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/api/chat': typeof ApiChatRoute
  '/app/avatar': typeof AppAvatarRoute
  '/app/chat': typeof AppChatRoute
  '/app/mascota': typeof AppMascotaRoute
  '/app/misiones': typeof AppMisionesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/recursos': typeof AppRecursosRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/juegos/cazadores': typeof AppJuegosCazadoresRoute
  '/app/juegos/conexion': typeof AppJuegosConexionRoute
  '/app/juegos/escudo': typeof AppJuegosEscudoRoute
  '/app/juegos/gratitud': typeof AppJuegosGratitudRoute
  '/app/juegos/memorama': typeof AppJuegosMemoramaRoute
  '/app/juegos/respira': typeof AppJuegosRespiraRoute
  '/app/juegos/semaforo': typeof AppJuegosSemaforoRoute
  '/app/juegos/trivia': typeof AppJuegosTriviaRoute
  '/app/juegos': typeof AppJuegosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/encuestas': typeof AdminEncuestasRoute
  '/admin/estudiantes': typeof AdminEstudiantesRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/api/chat': typeof ApiChatRoute
  '/app/avatar': typeof AppAvatarRoute
  '/app/chat': typeof AppChatRoute
  '/app/juegos': typeof AppJuegosRouteWithChildren
  '/app/mascota': typeof AppMascotaRoute
  '/app/misiones': typeof AppMisionesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/recursos': typeof AppRecursosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/juegos/cazadores': typeof AppJuegosCazadoresRoute
  '/app/juegos/conexion': typeof AppJuegosConexionRoute
  '/app/juegos/escudo': typeof AppJuegosEscudoRoute
  '/app/juegos/gratitud': typeof AppJuegosGratitudRoute
  '/app/juegos/memorama': typeof AppJuegosMemoramaRoute
  '/app/juegos/respira': typeof AppJuegosRespiraRoute
  '/app/juegos/semaforo': typeof AppJuegosSemaforoRoute
  '/app/juegos/trivia': typeof AppJuegosTriviaRoute
  '/app/juegos/': typeof AppJuegosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/admin/alertas'
    | '/admin/encuestas'
    | '/admin/estudiantes'
    | '/admin/noticias'
    | '/api/chat'
    | '/app/avatar'
    | '/app/chat'
    | '/app/juegos'
    | '/app/mascota'
    | '/app/misiones'
    | '/app/perfil'
    | '/app/recursos'
    | '/admin/'
    | '/app/'
    | '/app/juegos/cazadores'
    | '/app/juegos/conexion'
    | '/app/juegos/escudo'
    | '/app/juegos/gratitud'
    | '/app/juegos/memorama'
    | '/app/juegos/respira'
    | '/app/juegos/semaforo'
    | '/app/juegos/trivia'
    | '/app/juegos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/alertas'
    | '/admin/encuestas'
    | '/admin/estudiantes'
    | '/admin/noticias'
    | '/api/chat'
    | '/app/avatar'
    | '/app/chat'
    | '/app/mascota'
    | '/app/misiones'
    | '/app/perfil'
    | '/app/recursos'
    | '/admin'
    | '/app'
    | '/app/juegos/cazadores'
    | '/app/juegos/conexion'
    | '/app/juegos/escudo'
    | '/app/juegos/gratitud'
    | '/app/juegos/memorama'
    | '/app/juegos/respira'
    | '/app/juegos/semaforo'
    | '/app/juegos/trivia'
    | '/app/juegos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/admin/alertas'
    | '/admin/encuestas'
    | '/admin/estudiantes'
    | '/admin/noticias'
    | '/api/chat'
    | '/app/avatar'
    | '/app/chat'
    | '/app/juegos'
    | '/app/mascota'
    | '/app/misiones'
    | '/app/perfil'
    | '/app/recursos'
    | '/admin/'
    | '/app/'
    | '/app/juegos/cazadores'
    | '/app/juegos/conexion'
    | '/app/juegos/escudo'
    | '/app/juegos/gratitud'
    | '/app/juegos/memorama'
    | '/app/juegos/respira'
    | '/app/juegos/semaforo'
    | '/app/juegos/trivia'
    | '/app/juegos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/recursos': {
      id: '/app/recursos'
      path: '/recursos'
      fullPath: '/app/recursos'
      preLoaderRoute: typeof AppRecursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/misiones': {
      id: '/app/misiones'
      path: '/misiones'
      fullPath: '/app/misiones'
      preLoaderRoute: typeof AppMisionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mascota': {
      id: '/app/mascota'
      path: '/mascota'
      fullPath: '/app/mascota'
      preLoaderRoute: typeof AppMascotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/juegos': {
      id: '/app/juegos'
      path: '/juegos'
      fullPath: '/app/juegos'
      preLoaderRoute: typeof AppJuegosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/avatar': {
      id: '/app/avatar'
      path: '/avatar'
      fullPath: '/app/avatar'
      preLoaderRoute: typeof AppAvatarRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/noticias': {
      id: '/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminNoticiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estudiantes': {
      id: '/admin/estudiantes'
      path: '/estudiantes'
      fullPath: '/admin/estudiantes'
      preLoaderRoute: typeof AdminEstudiantesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/encuestas': {
      id: '/admin/encuestas'
      path: '/encuestas'
      fullPath: '/admin/encuestas'
      preLoaderRoute: typeof AdminEncuestasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alertas': {
      id: '/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AdminAlertasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/juegos/': {
      id: '/app/juegos/'
      path: '/'
      fullPath: '/app/juegos/'
      preLoaderRoute: typeof AppJuegosIndexRouteImport
      parentRoute: typeof AppJuegosRoute
    }
    '/app/juegos/trivia': {
      id: '/app/juegos/trivia'
      path: '/trivia'
      fullPath: '/app/juegos/trivia'
      preLoaderRoute: typeof AppJuegosTriviaRouteImport
      parentRoute: typeof AppJuegosRoute
    }
    '/app/juegos/semaforo': {
      id: '/app/juegos/semaforo'
      path: '/semaforo'
      fullPath: '/app/juegos/semaforo'
      preLoaderRoute: typeof AppJuegosSemaforoRouteImport
      parentRoute: typeof AppJuegosRoute
    }
    '/app/juegos/respira': {
      id: '/app/juegos/respira'
      path: '/respira'
      fullPath: '/app/juegos/respira'
      preLoaderRoute: typeof AppJuegosRespiraRouteImport
      parentRoute: typeof AppJuegosRoute
    }
    '/app/juegos/memorama': {
      id: '/app/juegos/memorama'
      path: '/memorama'
      fullPath: '/app/juegos/memorama'
      preLoaderRoute: typeof AppJuegosMemoramaRouteImport
      parentRoute: typeof AppJuegosRoute
    }
    '/app/juegos/gratitud': {
      id: '/app/juegos/gratitud'
      path: '/gratitud'
      fullPath: '/app/juegos/gratitud'
      preLoaderRoute: typeof AppJuegosGratitudRouteImport
      parentRoute: typeof AppJuegosRoute
    }
    '/app/juegos/escudo': {
      id: '/app/juegos/escudo'
      path: '/escudo'
      fullPath: '/app/juegos/escudo'
      preLoaderRoute: typeof AppJuegosEscudoRouteImport
      parentRoute: typeof AppJuegosRoute
    }
    '/app/juegos/conexion': {
      id: '/app/juegos/conexion'
      path: '/conexion'
      fullPath: '/app/juegos/conexion'
      preLoaderRoute: typeof AppJuegosConexionRouteImport
      parentRoute: typeof AppJuegosRoute
    }
    '/app/juegos/cazadores': {
      id: '/app/juegos/cazadores'
      path: '/cazadores'
      fullPath: '/app/juegos/cazadores'
      preLoaderRoute: typeof AppJuegosCazadoresRouteImport
      parentRoute: typeof AppJuegosRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertasRoute: typeof AdminAlertasRoute
  AdminEncuestasRoute: typeof AdminEncuestasRoute
  AdminEstudiantesRoute: typeof AdminEstudiantesRoute
  AdminNoticiasRoute: typeof AdminNoticiasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertasRoute: AdminAlertasRoute,
  AdminEncuestasRoute: AdminEncuestasRoute,
  AdminEstudiantesRoute: AdminEstudiantesRoute,
  AdminNoticiasRoute: AdminNoticiasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppJuegosRouteChildren {
  AppJuegosCazadoresRoute: typeof AppJuegosCazadoresRoute
  AppJuegosConexionRoute: typeof AppJuegosConexionRoute
  AppJuegosEscudoRoute: typeof AppJuegosEscudoRoute
  AppJuegosGratitudRoute: typeof AppJuegosGratitudRoute
  AppJuegosMemoramaRoute: typeof AppJuegosMemoramaRoute
  AppJuegosRespiraRoute: typeof AppJuegosRespiraRoute
  AppJuegosSemaforoRoute: typeof AppJuegosSemaforoRoute
  AppJuegosTriviaRoute: typeof AppJuegosTriviaRoute
  AppJuegosIndexRoute: typeof AppJuegosIndexRoute
}

const AppJuegosRouteChildren: AppJuegosRouteChildren = {
  AppJuegosCazadoresRoute: AppJuegosCazadoresRoute,
  AppJuegosConexionRoute: AppJuegosConexionRoute,
  AppJuegosEscudoRoute: AppJuegosEscudoRoute,
  AppJuegosGratitudRoute: AppJuegosGratitudRoute,
  AppJuegosMemoramaRoute: AppJuegosMemoramaRoute,
  AppJuegosRespiraRoute: AppJuegosRespiraRoute,
  AppJuegosSemaforoRoute: AppJuegosSemaforoRoute,
  AppJuegosTriviaRoute: AppJuegosTriviaRoute,
  AppJuegosIndexRoute: AppJuegosIndexRoute,
}

const AppJuegosRouteWithChildren = AppJuegosRoute._addFileChildren(
  AppJuegosRouteChildren,
)

interface AppRouteChildren {
  AppAvatarRoute: typeof AppAvatarRoute
  AppChatRoute: typeof AppChatRoute
  AppJuegosRoute: typeof AppJuegosRouteWithChildren
  AppMascotaRoute: typeof AppMascotaRoute
  AppMisionesRoute: typeof AppMisionesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRecursosRoute: typeof AppRecursosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvatarRoute: AppAvatarRoute,
  AppChatRoute: AppChatRoute,
  AppJuegosRoute: AppJuegosRouteWithChildren,
  AppMascotaRoute: AppMascotaRoute,
  AppMisionesRoute: AppMisionesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRecursosRoute: AppRecursosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
